### PR TITLE
Fix Stompy's Arrival Date (June 2021)

### LINKED ISSUE #64: Stompy moved in June 1st
https://www.youtube.com/watch?v=Qo_nlpqh8ig&t=1296s

### PR DESCRIPTION
**Pull request by nelsonfigueroa**
This PR fixes #64 (Stompy moved in June 1st). I also bumped the version.

### CODE REVIEW

File: src/ambassadors/core.ts [hunk 1]
```diff
@@ -45,7 +45,7 @@ const ambassadors = {
     scientific: "Dromaius novaehollandiae",
     sex: "Male",
     birth: "2021-02-14",
-    arrival: "2021-04",
+    arrival: "2021-06",
```
Comment (MattIPv4) [inline src/ambassadors/core.ts]:
```suggestion
    arrival: "2021-06-01",
```
Given we know it to be exactly June 1st, we can include that here

**Review by MattIPv4 — APPROVED** [review]
LGTM, ty
